"""
Android App Builder for PromptOps
==================================

Automated Android APK building with Gradle.
Supports signing, versioning, and multi-variant builds.

Author: DevOps Engineer
Date: 2026-05-10
"""

import os
import sys
import json
import logging
import subprocess
from typing import Dict, Any, Optional, List
from datetime import datetime
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(__file__))

try:
    from java_version_manager import JavaVersionManager
    JAVA_MANAGER_AVAILABLE = True
except ImportError:
    JAVA_MANAGER_AVAILABLE = False
    logger.warning("JavaVersionManager not available - using system Java")

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


# ============================================================================
# Android Builder
# ============================================================================

class AndroidBuilder:
    """
    Android application builder.

    Features:
    - Gradle-based APK building
    - Debug and release builds
    - APK signing
    - Version management
    - Multi-variant builds
    - Build artifact management
    """

    def __init__(self, project_path: str, auto_java_version: bool = True):
        """
        Initialize Android Builder.

        Args:
            project_path: Path to Android project root
            auto_java_version: Auto-detect and use compatible Java version
        """
        self.project_path = Path(project_path)
        self.auto_java_version = auto_java_version
        self.java_manager = None
        self.original_java_home = None

        # Initialize Java version manager if available
        if JAVA_MANAGER_AVAILABLE and auto_java_version:
            try:
                self.java_manager = JavaVersionManager()
                logger.info("Java Version Manager initialized")
            except Exception as e:
                logger.warning(f"Failed to initialize Java Manager: {e}")

        # Ensure Gradle wrapper exists
        self._ensure_gradle_wrapper()

        self.gradlew = self._find_gradlew()

    def _ensure_gradle_wrapper(self):
        """Ensure Gradle wrapper exists, install if missing."""
        if os.name == 'nt':
            gradlew = self.project_path / "gradlew.bat"
        else:
            gradlew = self.project_path / "gradlew"

        if not gradlew.exists():
            logger.warning(f"Gradle wrapper not found at {gradlew}")
            logger.info("Installing Gradle wrapper automatically...")
            try:
                self._install_gradle_wrapper()
                logger.info("Gradle wrapper installed successfully")
            except Exception as e:
                logger.error(f"Failed to install Gradle wrapper: {e}")
                raise FileNotFoundError(
                    f"Gradle wrapper not found at {gradlew}. "
                    f"Auto-installation failed: {e}"
                )

    def _install_gradle_wrapper(self):
        """Install Gradle wrapper in the project."""
        import urllib.request
        import zipfile
        import tempfile

        # Default to Gradle 8.0 if wrapper properties not found
        gradle_version = "8.0"

        # Try to detect version from gradle-wrapper.properties
        wrapper_props = self.project_path / "gradle" / "wrapper" / "gradle-wrapper.properties"
        if wrapper_props.exists():
            with open(wrapper_props, 'r') as f:
                for line in f:
                    if 'distributionUrl' in line:
                        # Extract version from URL like: gradle-8.0-bin.zip
                        import re
                        match = re.search(r'gradle-(\d+\.\d+)', line)
                        if match:
                            gradle_version = match.group(1)
                            break

        logger.info(f"Installing Gradle {gradle_version} wrapper...")

        # Download Gradle wrapper jar
        wrapper_jar_url = f"https://raw.githubusercontent.com/gradle/gradle/master/gradle/wrapper/gradle-wrapper.jar"
        wrapper_jar_path = self.project_path / "gradle" / "wrapper" / "gradle-wrapper.jar"

        os.makedirs(wrapper_jar_path.parent, exist_ok=True)

        try:
            urllib.request.urlretrieve(wrapper_jar_url, wrapper_jar_path)
        except Exception as e:
            logger.error(f"Failed to download gradle-wrapper.jar: {e}")
            # Create minimal wrapper scripts anyway
            pass

        # Create gradlew scripts
        if os.name == 'nt':
            gradlew_content = f"""@rem Gradle startup script for Windows
@rem Auto-generated by PromptOps

@if "%DEBUG%" == "" @echo off
setlocal enabledelayedexpansion

set DIRNAME=%~dp0
if "%DIRNAME%" == "" set DIRNAME=.
set APP_BASE_NAME=%~n0
set APP_HOME=%DIRNAME%

set JAVA_EXE=java.exe
if defined JAVA_HOME goto findJavaFromJavaHome

:findJavaFromJavaHome
set JAVA_HOME=%JAVA_HOME:"=%
set JAVA_EXE=%JAVA_HOME%/bin/java.exe

if exist "%JAVA_EXE%" goto execute

:execute
"%JAVA_EXE%" -classpath "%APP_HOME%\\gradle\\wrapper\\gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain %*

:end
"""
            gradlew_path = self.project_path / "gradlew.bat"
        else:
            gradlew_content = f"""#!/usr/bin/env sh
# Gradle startup script for Unix
# Auto-generated by PromptOps

DIRNAME="$(dirname "$0")"
APP_HOME="$DIRNAME"

if [ -n "$JAVA_HOME" ] ; then
    JAVA="$JAVA_HOME/bin/java"
else
    JAVA="java"
fi

exec "$JAVA" -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain "$@"
"""
            gradlew_path = self.project_path / "gradlew"

        with open(gradlew_path, 'w') as f:
            f.write(gradlew_content)

        # Make executable on Unix
        if os.name != 'nt':
            os.chmod(gradlew_path, 0o755)

        logger.info(f"Created {gradlew_path}")

    def _find_gradlew(self) -> str:
        """Find gradlew executable."""
        if os.name == 'nt':  # Windows
            gradlew = self.project_path / "gradlew.bat"
        else:  # Unix/Linux/Mac
            gradlew = self.project_path / "gradlew"

        if not gradlew.exists():
            raise FileNotFoundError(f"gradlew not found at {gradlew}")

        return str(gradlew)

    def _setup_compatible_java(self) -> Optional[Dict[str, str]]:
        """
        Setup compatible Java version for build.

        Returns:
            Environment variables dict with JAVA_HOME set, or None
        """
        if not self.java_manager:
            return None

        try:
            # Detect project requirements
            kotlin_version = self._detect_kotlin_version()
            gradle_version = self._detect_gradle_version()

            logger.info(f"Detected: Kotlin {kotlin_version}, Gradle {gradle_version}")

            # Get compatible Java version
            java_info = self.java_manager.get_compatible_java(
                kotlin_version=kotlin_version,
                gradle_version=gradle_version
            )

            if java_info and java_info['status'] == 'success':
                java_home = java_info['java_home']
                logger.info(f"Using Java {java_info['version']} from {java_home}")

                # Create environment with correct JAVA_HOME
                env = os.environ.copy()
                self.original_java_home = env.get('JAVA_HOME')
                env['JAVA_HOME'] = java_home
                env['PATH'] = f"{java_home}/bin{os.pathsep}{env['PATH']}"

                return env
            else:
                logger.warning(f"No compatible Java found: {java_info.get('message')}")
                return None

        except Exception as e:
            logger.warning(f"Failed to setup Java version: {e}")
            return None

    def _detect_kotlin_version(self) -> Optional[str]:
        """Detect Kotlin version from project."""
        # Try build.gradle.kts
        build_files = [
            self.project_path / "build.gradle.kts",
            self.project_path / "build.gradle",
            self.project_path / "app" / "build.gradle.kts",
            self.project_path / "app" / "build.gradle",
        ]

        for build_file in build_files:
            if build_file.exists():
                try:
                    with open(build_file, 'r', encoding='utf-8') as f:
                        content = f.read()
                        # Look for kotlin version
                        import re
                        patterns = [
                            r'kotlin[:\(]["\'](\d+\.\d+\.\d+)',
                            r'kotlin_version\s*=\s*["\'](\d+\.\d+\.\d+)',
                            r'org\.jetbrains\.kotlin.*:(\d+\.\d+\.\d+)',
                        ]
                        for pattern in patterns:
                            match = re.search(pattern, content)
                            if match:
                                return match.group(1)
                except Exception as e:
                    logger.debug(f"Error reading {build_file}: {e}")

        return None

    def _detect_gradle_version(self) -> Optional[str]:
        """Detect Gradle version from wrapper properties."""
        wrapper_props = self.project_path / "gradle" / "wrapper" / "gradle-wrapper.properties"
        if wrapper_props.exists():
            try:
                with open(wrapper_props, 'r') as f:
                    for line in f:
                        if 'distributionUrl' in line:
                            import re
                            match = re.search(r'gradle-(\d+\.\d+)', line)
                            if match:
                                return match.group(1)
            except Exception as e:
                logger.debug(f"Error reading gradle wrapper: {e}")

        return None

    def build_debug_apk(
        self,
        module: str = "app"
    ) -> Dict[str, Any]:
        """
        Build debug APK.

        Args:
            module: Android module name

        Returns:
            Build result with APK path
        """
        logger.info(f"Building debug APK for module: {module}")

        start_time = datetime.utcnow()

        try:
            # Setup compatible Java version if available
            env = self._setup_compatible_java()

            # If no compatible Java found, try Docker
            if env is None:
                logger.warning("No compatible Java found locally")
                logger.info("Attempting Docker build as fallback...")

                try:
                    from docker_builder import DockerAndroidBuilder
                    docker_builder = DockerAndroidBuilder(str(self.project_path))

                    if docker_builder.is_docker_available():
                        logger.info("Docker is available - using Docker build")
                        return docker_builder.build_apk_with_docker(module)
                    else:
                        logger.warning("Docker not available either")
                except Exception as e:
                    logger.error(f"Docker build attempt failed: {e}")

                # If we get here, neither Java nor Docker is available
                return {
                    "status": "failed",
                    "error": "No compatible Java version found and Docker not available.\n\n" +
                            "Options:\n" +
                            "1. Install Java 17 from: https://adoptium.net/teapot/\n" +
                            "2. Install Docker Desktop from: https://www.docker.com/products/docker-desktop\n" +
                            "3. Use Gitpod (cloud): https://gitpod.io/#https://github.com/kirankumarhs29/netSenseAI"
                }

            java_version_used = env.get('JAVA_HOME', 'system default') if env else 'system default'

            # Run Gradle build
            cmd = [self.gradlew, f":{module}:assembleDebug"]
            result = subprocess.run(
                cmd,
                cwd=self.project_path,
                capture_output=True,
                text=True,
                timeout=600,
                env=env  # Use custom environment with correct JAVA_HOME
            )

            duration = (datetime.utcnow() - start_time).total_seconds()

            if result.returncode == 0:
                apk_path = self._find_apk(module, "debug")

                # Get APK size
                apk_size_mb = None
                if apk_path:
                    apk_size_mb = round(Path(apk_path).stat().st_size / (1024 * 1024), 2)

                return {
                    "status": "success",
                    "module": module,
                    "build_type": "debug",
                    "apk_path": str(apk_path) if apk_path else None,
                    "apk_size_mb": apk_size_mb,
                    "duration_seconds": duration,
                    "build_duration": f"{int(duration // 60)}m {int(duration % 60)}s",
                    "java_version": java_version_used,
                    "build_log": result.stdout[-500:] if result.stdout else "",
                    "built_at": datetime.utcnow().isoformat()
                }
            else:
                logger.error(f"Build failed: {result.stderr}")
                return {
                    "status": "failed",
                    "module": module,
                    "build_type": "debug",
                    "error": result.stderr[-500:] if result.stderr else "Build failed",
                    "duration_seconds": duration
                }

        except subprocess.TimeoutExpired:
            return {
                "status": "timeout",
                "module": module,
                "error": "Build timeout after 600 seconds"
            }
        except Exception as e:
            logger.error(f"Build exception: {e}")
            return {
                "status": "error",
                "module": module,
                "error": str(e)
            }

    def build_release_apk(
        self,
        module: str = "app",
        keystore_path: Optional[str] = None,
        keystore_password: Optional[str] = None,
        key_alias: Optional[str] = None,
        key_password: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Build release APK with signing.

        Args:
            module: Android module name
            keystore_path: Path to keystore file
            keystore_password: Keystore password
            key_alias: Key alias
            key_password: Key password

        Returns:
            Build result with signed APK path
        """
        logger.info(f"Building release APK for module: {module}")

        start_time = datetime.utcnow()

        try:
            cmd = [self.gradlew, f":{module}:assembleRelease"]

            # Setup compatible Java version if available
            env = self._setup_compatible_java()
            if env is None:
                env = os.environ.copy()

            # Add signing configuration if provided
            if keystore_path:
                env["KEYSTORE_PATH"] = keystore_path
                env["KEYSTORE_PASSWORD"] = keystore_password or ""
                env["KEY_ALIAS"] = key_alias or ""
                env["KEY_PASSWORD"] = key_password or ""

            result = subprocess.run(
                cmd,
                cwd=self.project_path,
                capture_output=True,
                text=True,
                timeout=600,
                env=env
            )

            duration = (datetime.utcnow() - start_time).total_seconds()

            if result.returncode == 0:
                apk_path = self._find_apk(module, "release")

                return {
                    "status": "success",
                    "module": module,
                    "build_type": "release",
                    "signed": bool(keystore_path),
                    "apk_path": str(apk_path) if apk_path else None,
                    "duration_seconds": duration,
                    "built_at": datetime.utcnow().isoformat()
                }
            else:
                return {
                    "status": "failed",
                    "module": module,
                    "build_type": "release",
                    "error": result.stderr[-500:] if result.stderr else "Build failed",
                    "duration_seconds": duration
                }

        except Exception as e:
            logger.error(f"Release build exception: {e}")
            return {
                "status": "error",
                "module": module,
                "error": str(e)
            }

    def _find_apk(self, module: str, build_type: str) -> Optional[Path]:
        """Find built APK file."""
        build_dir = self.project_path / module / "build" / "outputs" / "apk" / build_type

        if not build_dir.exists():
            logger.warning(f"Build directory not found: {build_dir}")
            return None

        apk_files = list(build_dir.glob("*.apk"))

        if not apk_files:
            logger.warning(f"No APK files found in {build_dir}")
            return None

        # Return the first APK (or most recent if multiple)
        return sorted(apk_files, key=lambda p: p.stat().st_mtime)[-1]

    def clean_build(self) -> Dict[str, Any]:
        """
        Clean build artifacts.

        Returns:
            Clean result
        """
        logger.info("Cleaning build artifacts")

        try:
            cmd = [self.gradlew, "clean"]
            result = subprocess.run(
                cmd,
                cwd=self.project_path,
                capture_output=True,
                text=True,
                timeout=120
            )

            return {
                "status": "success" if result.returncode == 0 else "failed",
                "cleaned_at": datetime.utcnow().isoformat()
            }

        except Exception as e:
            return {
                "status": "error",
                "error": str(e)
            }

    def get_version_info(self, module: str = "app") -> Dict[str, Any]:
        """
        Extract version information from build.gradle.

        Args:
            module: Module name

        Returns:
            Version information
        """
        logger.info("Extracting version information")

        try:
            gradle_file = self.project_path / module / "build.gradle.kts"
            if not gradle_file.exists():
                gradle_file = self.project_path / module / "build.gradle"

            if not gradle_file.exists():
                return {
                    "status": "error",
                    "error": "build.gradle file not found"
                }

            with open(gradle_file, 'r') as f:
                content = f.read()

            # Simple parsing (would need more robust parsing for production)
            version_code = self._extract_value(content, "versionCode")
            version_name = self._extract_value(content, "versionName")

            return {
                "status": "success",
                "version_code": version_code,
                "version_name": version_name,
                "gradle_file": str(gradle_file)
            }

        except Exception as e:
            return {
                "status": "error",
                "error": str(e)
            }

    def _extract_value(self, content: str, key: str) -> Optional[str]:
        """Extract value from gradle file."""
        import re

        pattern = rf'{key}\s*=?\s*["\']?(\d+\.?\d*\.?\d*)["\']?'
        match = re.search(pattern, content)

        return match.group(1) if match else None

    def list_build_variants(self) -> List[str]:
        """
        List available build variants.

        Returns:
            List of variant names
        """
        # Default Android variants
        return ["debug", "release"]


# ============================================================================
# Testing
# ============================================================================

def test_android_builder():
    """Test Android Builder."""
    logger.info("Testing Android Builder...")

    # Mock project path
    project_path = "/path/to/android/project"

    print("\n=== Android Builder Demo ===")
    print(f"Project Path: {project_path}")
    print("\nNote: This is a demonstration. Actual build requires:")
    print("  - Valid Android project with gradlew")
    print("  - Android SDK installed")
    print("  - Java/Kotlin environment")

    print("\n=== Build Process ===")
    print("1. Clean build artifacts")
    print("2. Build debug APK (assembleDebug)")
    print("3. Find APK in build/outputs/apk/debug/")
    print("4. Extract version info from build.gradle")

    print("\n=== Example Output ===")
    example_result = {
        "status": "success",
        "module": "app",
        "build_type": "debug",
        "apk_path": "/project/app/build/outputs/apk/debug/app-debug.apk",
        "duration_seconds": 45.3,
        "built_at": datetime.utcnow().isoformat()
    }
    print(json.dumps(example_result, indent=2))


if __name__ == "__main__":
    test_android_builder()
